/* Generated by Yosys 0.59+62 (git sha1 9aa2dde7e, clang++ 18.1.8 -fPIC -O3) */

module tt_um_example(ui_in, uio_in, ena, clk, rst_n, uo_out, uio_out, uio_oe);
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  input ena;
  wire ena;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  output [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uio_oe;
  wire [7:0] uio_oe;
  wire _0_;
  reg [7:0] _1_ = 8'h00;
  wire [7:0] \reg ;
  always @(posedge clk, posedge _0_)
    if (_0_) _1_ <= 8'h00;
    else _1_ <= { ui_in[0], \reg [7:1] };
  assign _0_ = ~ rst_n;
  assign \reg  = _1_;
  assign uo_out = \reg ;
  assign uio_out = 8'hzz;
  assign uio_oe = 8'hzz;
endmodule
